name: ci

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Remove linkstack folder
        run: rm -rf linkstack
      - name: Checkout linkstack
        uses: actions/checkout@v4
        with:
          repository: LinkStackOrg/LinkStack
          ref: ${{ github.ref_name }}
          path: linkstack
      - name: Test run ls
        run: ls -al
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: prakashdivyy/linkstack:${{ github.ref_name }}
